# Site settings
title: Serena Chen
email: serenadantingchen@gmail.com
description: Digital product designer solving complex problems at scale.
baseurl: ""
url: "https://serena.nz"
twitter_username: Sereeena
github_username:  heisenburger

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# trigger build